004 revisions
wmo-im/wcmp pull request #134
Opened 2022-07-04 20:07 UTC by amilan17

2022-07-05 15:22 UTC, amilan17 commented
For review: 

*    [ ]  removal of XML examples that are duplicative of existing guidance. 

For discussion: 

*    [ ]  Why is there a distinct test for presence of temporal elements? Is it to give a score just for the existence of anything time related?

2022-07-06 12:45 UTC, amilan17 commented
keep test for temporal extent (no s)

2022-07-12 10:59 UTC, tomkralidis requested changes

2022-07-12 10:59 UTC, tomkralidis commented on kpi/004-temporal-information.adoc
> +|The temporal `extent` section is present.
The `gmd:temporalExtent` element is present

2022-07-12 10:59 UTC, tomkralidis commented on kpi/004-temporal-information.adoc
> +|The `beginPosition` and `endPosition` elements are present in the temporal extent.
`gml:beginPosition` && `gml:endPosition`

2022-07-12 10:59 UTC, tomkralidis commented on kpi/004-temporal-information.adoc
> +|The `maintenanceAndUpdateFrequency` elements are present.
`gmd:maintenanceAndUpdateFrequency`

2022-07-12 10:59 UTC, tomkralidis commented on kpi/004-temporal-information.adoc
> +|The `status` element is present.
`gmd:status`

2022-07-13 14:35 UTC, merged