006-keywords revisions
wmo-im/wcmp pull request #135
Opened 2022-07-05 13:31 UTC by amilan17

2022-07-06 11:13 UTC, amilan17 commented
for discussion: 

- [ ] what does this mean: " compliance to WCMP 1.3 defines a set of rules that apply to different
sets of keywords"

2022-07-06 14:25 UTC, josusky commented
> In addition to measure well-defined references to dictionaries and keyword types, compliance to WCMP 1.3 defines a set of rules that apply to different sets of keywords that are not included in this measurement.
My long-term memory is poor, but it seems to me that this sentence might have been a reference to KPI-9, where the "scope of distribution" is expressed as a keyword. So here in KPI 6 we only check that it has the correct form (thesaurus etc.) but in KPI-9 we check also the content (e.g. controlled vocabulary).

2022-07-08 09:11 UTC, amilan17 commented
*    [ ]  need to describe scoring better

2022-07-12 10:53 UTC, tomkralidis requested changes

2022-07-12 10:53 UTC, tomkralidis commented on kpi/006-keywords.adoc
> +|6.1: There are one to many `keyword` elements present.
`gmd:keyword`

2022-07-12 10:53 UTC, tomkralidis commented on kpi/006-keywords.adoc
> +a|6.3: The `title` element for the thesuarus name is present.
`gmd:title`

2022-07-12 10:53 UTC, tomkralidis commented on kpi/006-keywords.adoc
> +a|6.4: Keywords and thesaurus names are implemented in the `Anchor` element .
`gmx:Anchor`

2022-07-12 10:53 UTC, tomkralidis commented on kpi/006-keywords.adoc
> +The `keyword` value is included in an `Anchor` element with a resolvable HTTP URL.
`gmd:keyword` && `gmx:Anchor`

2022-07-12 10:53 UTC, tomkralidis commented on kpi/006-keywords.adoc
> +The `type` of keyword is given in `MD_KeywordTypeCode` element, the "codelist" indicates URL of the code list.
`gmd:type`

2022-07-14 12:53 UTC, tomkralidis approved these changes

2022-07-14 12:53 UTC, merged