KPI F updates
wmo-im/wcmp pull request #76
Opened 2020-12-08 02:57 UTC by tomkralidis

@martaguti I took the liberty of updating some of the text while updating the structure per #71.

There is a note here in the KPI about merging with KPI K (for review/comment).

2020-12-08 23:02 UTC, martaguti commented
@tomkralidis thanks so much for formatting this and making so much progress! 

It does not merge with K, at the time we discussed that to merge with k as it was dealing with WMOLicenceCode.
But K does not check the link for WMOEssential, so it can stay as it is. 

I guess F checks the presence of link, and KPI J will check that the link itself is a good one.

2020-12-08 23:09 UTC, martaguti requested changes

2020-12-08 23:09 UTC, martaguti commented on KPI/F.adoc
> +Draft (*To be merge with K* ?)
Line 5 can go

2020-12-08 23:09 UTC, martaguti commented on KPI/F.adoc
> +.Temporal information implementation rules
Update to : WMOEssential data links implementation rules

2020-12-08 23:09 UTC, martaguti commented on KPI/F.adoc
> +|DataLicenseCode is `WMOEssential` and 1..n valid distribution links are provided
That should say that links are not provided / invalid ?  with -1

2020-12-09 02:42 UTC, tomkralidis commented
Thanks for the feedback @martaguti.  PR updated for review/comment.

2020-12-16 20:35 UTC, martaguti commented
@tomkralidis @gaubert  please review 

removed the validation of the links as discussed in the meeting.

We don't care in this one how many links the put . If there is one or 20 they just get the score ... 
We don't give negative scores for invalid ones as that belongs to J again

2020-12-16 23:38 UTC, tomkralidis commented
Thanks @martaguti, makes sense/+1,  @gaubert ?

2021-01-08 06:35 UTC, jsieland commented on KPI/F.adoc
> +      </gmd:protocol>
Comment from my GISC Offenbach colleagues:
- a list for allowd values ("http", "https") instead of free text
- need as anchor

2021-01-08 06:40 UTC, jsieland commented on KPI/F.adoc
> +      </gmd:name>
Comment from my GISC Offenbach colleagues:
- name linked to fixed value for data link, e.g. "dataLink"

2021-01-08 09:45 UTC, gaubert commented
> Thanks @martaguti, makes sense/+1, @gaubert ?

Yes that's fine with me as well.

2021-01-22 21:47 UTC, tomkralidis commented
@martaguti @jsieland @gaubert for some reason this was shown as completed on #68, and thus we did not discuss it today.  I've since changed its status.  It still needs approval.

The last discussion I see is from our [2020-01-08 meeting](https://github.com/wmo-im/wcmp/wiki/Meeting-2021-01-08#notes) (DECISION: don’t integrate protocol BPs; ready for PR).  I believe this meant for us not to dive into `gmd:protocol` lists/best practices (hence #84 since created)?

Please let me know with an approval here is this is good for merge or requires further discussion.  Thanks.

2021-01-27 19:32 UTC, martaguti commented
@tomkralidis  
This is good to merge, we decided this two meetings ago.
We also decided not to go into protocol lists for now.

2021-01-27 22:18 UTC, merged